### ISSUE TITLE
A question about Data unbalance

### ISSUE THREAD

**Issue by Chic-J** [MDFahimAnjum/LightCNNforPD#1]
Hello, this is a great article. After reading your article, I have been inspired a lot. I am also using the UNM Dataset for some classification work, but there is an issue of sample imbalance in the UNM Dataset. I noticed that your article has selected an equal number of healthy and diseased samples. May I ask which specific sample numbers you have chosen? And do you have any thoughts on sample imbalance? thank you

**Comment by Chic-J** [comment]
I wonder what is your data preproccessing?

**Comment by MDFahimAnjum** [comment]
Hi, thank you so much for reading the article and your kind feedback!

- Regarding the class imbalance, the UNM dataset has an equal amount of participants and if you take the first one minute as mentioned in the methods, you should end up with a balanced class. Here is the UNM website where you can get the datasets (along with other similar EEG datasets as well) http://predict.cs.unm.edu/downloads.php 

- Regarding data preprocessing, it's just a highpass filter to avoid EEG drifts and DC offsets. I have added the scripts to the repo in the Matlab Codes folder. You will need Matlab and EEGLab plugin to run the script. The script will generate CSV files and plots which you can manually inspect to see which data were too corrupted with noise and you can ignore those. 

Hope this helps and thanks again!
